version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: feedback_restaurante
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - towersfy_network
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - towersfy_network
    volumes:
      - redis_data:/data

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: feedback_restaurante
      DB_USER: postgres
      DB_PASSWORD: mypass
    command: >
      /bin/sh -c "
        echo 'Waiting for database to be ready...'
        sleep 15
        npx sequelize-cli db:migrate &&
        npx sequelize-cli db:seed:all
      "
    networks:
      - towersfy_network
    volumes:
      - .:/app

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - migrations
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: feedback_restaurante
      DB_USER: postgres
      DB_PASSWORD: mypass
      JWT_SECRET: devsecret
      REDIS_URL: redis://redis:6379
    ports:
      - "5000:5000"
    networks:
      - towersfy_network
    volumes:
      - uploads_data:/app/backend/public/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    ports:
      - "3000:80"
    networks:
      - towersfy_network

networks:
  towersfy_network:
    driver: bridge

volumes:
  uploads_data:
  postgres_data:
  redis_data:
