import {
  Dashboard as DashboardIcon,
  CheckBox as CheckinIcon,
  Star as SatisfactionIcon,
  Chat as ResponsesIcon,
  ConnectWithoutContact as RelationshipIcon,
  CardGiftcard as CouponsIcon,
  Sync as AutomationIcon,
  Settings as IntegrationsIcon,
  Assessment as ReportsIcon,
  Inventory as StockIcon,
  Receipt as OrdersIcon,
  Group as ManagementIcon,
  Label as CdvIcon,
  MonetizationOn as FinancialIcon,
  Settings as SettingsIcon,
  AdminPanelSettings as AdminIcon,
} from '@mui/icons-material';

export const menuStructure = [
  {
    module: 'fidelity',
    title: 'Fidelidade',
    icon: <DashboardIcon />,
    roles: ['admin', 'owner', 'manager'],
    submenu: [
      {
        title: 'Geral',
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Painel Inicial',
            path: '/fidelity/dashboard',
            featureKey: 'fidelity:general:dashboard',
            actionKey: 'read',
          },
          {
            title: 'Resumo do mês',
            path: '/fidelity/monthly-summary',
            featureKey: 'fidelity:general:dashboard', // Corrected feature key
            actionKey: 'read',
          },
          {
            title: 'Satisfação',
            path: '/fidelity/satisfaction-overview',
            featureKey: 'fidelity:general:dashboard', // Corrected feature key
            actionKey: 'read',
          },
          {
            title: 'Comparativo Pesquisas',
            path: '/fidelity/surveys-comparison',
            featureKey: 'surveys_comparison',
            actionKey: 'read',
          },
          {
            title: 'Resumo do mês',
            path: '/fidelity/monthly-summary',
            featureKey: 'fidelity:general:monthly-summary',
            actionKey: 'read',
          },
          {
            title: 'Satisfação',
            path: '/fidelity/satisfaction-overview',
            featureKey: 'fidelity:general:satisfaction-overview',
            actionKey: 'read',
          },
          {
            title: 'Comparativo Pesquisas',
            path: '/fidelity/surveys-comparison',
            featureKey: 'fidelity:general:surveys-comparison',
            actionKey: 'read',
          },
          {
            title: 'Evolução',
            path: '/fidelity/evolution',
            featureKey: 'fidelity:general:evolution',
            actionKey: 'read',
          },
          {
            title: 'Benchmarking',
            path: '/fidelity/benchmarking',
            featureKey: 'fidelity:general:benchmarking',
            actionKey: 'read',
          },
          {
            title: 'Multipla Escolha',
            path: '/fidelity/multiple-choice',
            featureKey: 'fidelity:general:multiple-choice',
            actionKey: 'read',
          },
          {
            title: 'Nuvens de Palavras',
            path: '/fidelity/word-clouds',
            featureKey: 'fidelity:general:word-clouds',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Check in',
        icon: <CheckinIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Dashboard',
            path: '/fidelity/checkin/dashboard',
            featureKey: 'fidelity:checkin:dashboard',
            actionKey: 'read',
          },
          {
            title: 'Configurações',
            path: '/fidelity/checkin/settings',
            featureKey: 'fidelity:checkin:settings',
            actionKey: 'read',
          },
          {
            title: 'Checkin Ativos',
            path: '/fidelity/checkin/active',
            featureKey: 'fidelity:checkin:active',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Satisfação',
        icon: <SatisfactionIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Dashboard',
            path: '/fidelity/satisfaction/dashboard',
            featureKey: 'fidelity:satisfaction:dashboard',
            actionKey: 'read',
          },
          {
            title: 'Configurações',
            path: '/fidelity/satisfaction/settings',
            featureKey: 'fidelity:satisfaction:settings',
            actionKey: 'read',
          },
          {
            title: 'Pesquisas',
            path: '/fidelity/satisfaction/surveys',
            featureKey: 'fidelity:satisfaction:surveys',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Respostas',
        icon: <ResponsesIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Painel',
            path: '/fidelity/responses/dashboard',
            featureKey: 'fidelity:responses:dashboard',
            actionKey: 'read',
          },
          {
            title: 'Gestão as Respostas',
            path: '/fidelity/responses/management',
            featureKey: 'fidelity:responses:management',
            actionKey: 'read',
          },
          {
            title: 'Replicas',
            path: '/fidelity/responses/replicas',
            featureKey: 'fidelity:responses:replicas',
            actionKey: 'read',
          },
          {
            title: 'Metas',
            path: '/fidelity/responses/goals',
            featureKey: 'fidelity:responses:goals',
            actionKey: 'read',
          },
          {
            title: 'Importar',
            path: '/fidelity/responses/import',
            featureKey: 'fidelity:responses:import',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Relacionamento',
        icon: <RelationshipIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Dashboard',
            path: '/fidelity/relationship/dashboard',
            featureKey: 'fidelity:relationship:dashboard',
            actionKey: 'read',
          },
          {
            title: 'Ranking de Clientes',
            path: '/fidelity/relationship/ranking',
            featureKey: 'fidelity:relationship:ranking',
            actionKey: 'read',
          },
          {
            title: 'Disparos',
            path: '/fidelity/relationship/dispatches',
            featureKey: 'fidelity:relationship:dispatches',
            actionKey: 'read',
          },
          {
            title: 'Campanhas Automaticas',
            path: '/fidelity/relationship/campaigns',
            featureKey: 'fidelity:relationship:campaigns',
            actionKey: 'read',
          },
          {
            title: 'Mensagens',
            path: '/fidelity/relationship/messages',
            featureKey: 'fidelity:relationship:messages',
            actionKey: 'read',
          },
          {
            title: 'Aniversariantes',
            path: '/fidelity/relationship/birthdays',
            featureKey: 'fidelity:relationship:birthdays',
            actionKey: 'read',
          },
          {
            title: 'Gestão de Clientes',
            path: '/fidelity/relationship/customers',
            featureKey: 'fidelity:relationship:customers',
            actionKey: 'read',
          },
          {
            title: 'Segmentação de Clientes',
            path: '/fidelity/relationship/segmentation',
            featureKey: 'fidelity:relationship:segmentation',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Cupons',
        icon: <CouponsIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Painel',
            path: '/fidelity/coupons/dashboard',
            featureKey: 'fidelity:coupons:dashboard',
            actionKey: 'read',
          },
          {
            title: 'Cupons',
            path: '/fidelity/coupons/list',
            featureKey: 'fidelity:coupons:list',
            actionKey: 'read',
          },
          {
            title: 'Gestão de Cupons',
            path: '/fidelity/coupons/management',
            featureKey: 'fidelity:coupons:management',
            actionKey: 'read',
          },
          {
            title: 'Validação',
            path: '/fidelity/coupons/validation',
            featureKey: 'fidelity:coupons:validation',
            actionKey: 'read',
          },
          {
            title: 'Sorteio',
            path: '/fidelity/coupons/raffle',
            featureKey: 'fidelity:coupons:raffle',
            actionKey: 'read',
          },
          {
            title: 'Recompensas',
            path: '/fidelity/coupons/rewards',
            featureKey: 'fidelity:coupons:rewards',
            actionKey: 'read',
          },
          {
            title: 'Gestão de Recompensas',
            path: '/fidelity/coupons/rewards-management',
            featureKey: 'fidelity:coupons:rewards-management',
            actionKey: 'read',
          },
          {
            title: 'Cadastro de Recompensas',
            path: '/fidelity/coupons/rewards-create',
            featureKey: 'fidelity:coupons:rewards-create',
            actionKey: 'create',
          },
          {
            title: 'Relatorios de Resgate',
            path: '/fidelity/coupons/redemption-reports',
            featureKey: 'fidelity:coupons:redemption-reports',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Automação',
        icon: <AutomationIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Fluxos',
            path: '/fidelity/automation/flows',
            featureKey: 'fidelity:automation:flows',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Integrações',
        icon: <IntegrationsIcon />,
        path: '/fidelity/integrations',
        featureKey: 'fidelity:integrations',
        actionKey: 'read',
      },
      {
        title: 'Relatorios',
        icon: <ReportsIcon />,
        path: '/fidelity/reports',
        featureKey: 'fidelity:reports',
        actionKey: 'read',
      },
    ],
  },
          {
            title: 'Benchmarking',
            path: '/fidelity/benchmarking',
            featureKey: 'benchmarking',
            actionKey: 'read',
          },
          {
            title: 'Multipla Escolha',
            path: '/fidelity/multiple-choice',
            featureKey: 'multiple_choice',
            actionKey: 'read',
          },
          {
            title: 'Nuvens de Palavras',
            path: '/fidelity/word-clouds',
            featureKey: 'fidelity:general:word-clouds',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Check in',
        icon: <CheckinIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Dashboard',
            path: '/fidelity/checkin/dashboard',
            featureKey: 'checkin_dashboard',
            actionKey: 'read',
          },
          {
            title: 'Configurações',
            path: '/fidelity/checkin/settings',
            featureKey: 'fidelity:checkin:settings',
            actionKey: 'read',
          },
          {
            title: 'Checkin Ativos',
            path: '/fidelity/checkin/active',
            featureKey: 'checkin_active',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Satisfação',
        icon: <SatisfactionIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Dashboard',
            path: '/fidelity/satisfaction/dashboard',
            featureKey: 'satisfaction_dashboard',
            actionKey: 'read',
          },
          {
            title: 'Configurações',
            path: '/fidelity/satisfaction/settings',
            featureKey: 'fidelity:satisfaction:settings',
            actionKey: 'read',
          },
          {
            title: 'Pesquisas',
            path: '/fidelity/satisfaction/surveys',
            featureKey: 'fidelity:satisfaction:surveys',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Respostas',
        icon: <ResponsesIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Painel',
            path: '/fidelity/responses/dashboard',
            featureKey: 'responses_dashboard',
            actionKey: 'read',
          },
          {
            title: 'Gestão as Respostas',
            path: '/fidelity/responses/management',
            featureKey: 'responses_management',
            actionKey: 'read',
          },
          {
            title: 'Replicas',
            path: '/fidelity/responses/replicas',
            featureKey: 'responses_replicas',
            actionKey: 'read',
          },
          {
            title: 'Metas',
            path: '/fidelity/responses/goals',
            featureKey: 'responses_goals',
            actionKey: 'read',
          },
          {
            title: 'Importar',
            path: '/fidelity/responses/import',
            featureKey: 'fidelity:responses:import',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Relacionamento',
        icon: <RelationshipIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Dashboard',
            path: '/fidelity/relationship/dashboard',
            featureKey: 'relationship_dashboard',
            actionKey: 'read',
          },
          {
            title: 'Ranking de Clientes',
            path: '/fidelity/relationship/ranking',
            featureKey: 'relationship_ranking',
            actionKey: 'read',
          },
          {
            title: 'Disparos',
            path: '/fidelity/relationship/dispatches',
            featureKey: 'relationship_dispatches',
            actionKey: 'read',
          },
          {
            title: 'Campanhas Automaticas',
            path: '/fidelity/relationship/campaigns',
            featureKey: 'relationship_campaigns',
            actionKey: 'read',
          },
          {
            title: 'Mensagens',
            path: '/fidelity/relationship/messages',
            featureKey: 'relationship_messages',
            actionKey: 'read',
          },
          {
            title: 'Aniversariantes',
            path: '/fidelity/relationship/birthdays',
            featureKey: 'relationship_birthdays',
            actionKey: 'read',
          },
          {
            title: 'Gestão de Clientes',
            path: '/fidelity/relationship/customers',
            featureKey: 'relationship_customers',
            actionKey: 'read',
          },
          {
            title: 'Segmentação de Clientes',
            path: '/fidelity/relationship/segmentation',
            featureKey: 'fidelity:relationship:segmentation',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Cupons',
        icon: <CouponsIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Painel',
            path: '/fidelity/coupons/dashboard',
            featureKey: 'coupons_dashboard',
            actionKey: 'read',
          },
          {
            title: 'Cupons',
            path: '/fidelity/coupons/list',
            featureKey: 'coupons_list',
            actionKey: 'read',
          },
          {
            title: 'Gestão de Cupons',
            path: '/fidelity/coupons/management',
            featureKey: 'coupons_management',
            actionKey: 'read',
          },
          {
            title: 'Validação',
            path: '/fidelity/coupons/validation',
            featureKey: 'coupons_validation',
            actionKey: 'read',
          },
          {
            title: 'Sorteio',
            path: '/fidelity/coupons/raffle',
            featureKey: 'coupons_raffle',
            actionKey: 'read',
          },
          {
            title: 'Recompensas',
            path: '/fidelity/coupons/rewards',
            featureKey: 'coupons_rewards',
            actionKey: 'read',
          },
          {
            title: 'Gestão de Recompensas',
            path: '/fidelity/coupons/rewards-management',
            featureKey: 'coupons_rewards_management',
            actionKey: 'read',
          },
          {
            title: 'Cadastro de Recompensas',
            path: '/fidelity/coupons/rewards-create',
            featureKey: 'coupons_rewards_create',
            actionKey: 'create',
          },
          {
            title: 'Relatorios de Resgate',
            path: '/fidelity/coupons/redemption-reports',
            featureKey: 'fidelity:coupons:redemption-reports',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Automação',
        icon: <AutomationIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Fluxos',
            path: '/fidelity/automation/flows',
            featureKey: 'fidelity:automation:flows',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Integrações',
        icon: <IntegrationsIcon />,
        path: '/fidelity/integrations',
        featureKey: 'fidelity_integrations',
        actionKey: 'read',
      },
      {
        title: 'Relatorios',
        icon: <ReportsIcon />,
        path: '/fidelity/reports',
        featureKey: 'fidelity:reports',
        actionKey: 'read',
      },
    ],
  },
  {
    module: 'stock',
    title: 'Estoque',
    icon: <StockIcon />,
    roles: ['admin', 'owner', 'manager'],
    submenu: [
      {
        title: 'Dashboard',
        path: '/stock/dashboard',
        featureKey: 'stock_dashboard',
        actionKey: 'read',
      },
      {
        title: 'Movimentações',
        path: '/stock/movements',
        featureKey: 'stock_movements',
        actionKey: 'read',
      },
      {
        title: 'Fornecedores',
        path: '/stock/suppliers',
        featureKey: 'stock_suppliers',
        actionKey: 'read',
      },
      {
        title: 'Compras',
        path: '/stock/purchases',
        featureKey: 'stock_purchases',
        actionKey: 'read',
      },
      { title: 'Vendas', path: '/stock/sales', featureKey: 'stock_sales', actionKey: 'read' },
      {
        title: 'Produtos',
        path: '/stock/products',
        featureKey: 'stock_products',
        actionKey: 'read',
      },
      {
        title: 'Cadastro de Produtos',
        path: '/stock/products/create',
        featureKey: 'stock_products_create',
        actionKey: 'create',
      },
      {
        title: 'Ingredientes e Insumos',
        path: '/stock/ingredients',
        featureKey: 'stock_ingredients',
        actionKey: 'read',
      },
      {
        title: 'Configurações',
        path: '/stock/settings',
        featureKey: 'stock_settings',
        actionKey: 'read',
      },
      {
        title: 'Relatorios',
        path: '/stock/reports',
        featureKey: 'stock_reports',
        actionKey: 'read',
      },
      {
        title: 'Contagem de Estoque',
        path: '/cdv/stock-counts',
        featureKey: 'cdv_stock_counts',
        actionKey: 'read',
      },
      {
        title: 'Inventario',
        path: '/stock/inventory',
        featureKey: 'stock_inventory',
        actionKey: 'read',
      },
      {
        title: 'Ficha Tecnica',
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Cadastro',
            path: '/stock/technical-sheet/create',
            featureKey: 'stock_technical_sheet_create',
            actionKey: 'create',
          },
          {
            title: 'Fichas Tecnicas',
            path: '/stock/technical-sheet/list',
            featureKey: 'stock_technical_sheet_list',
            actionKey: 'read',
          },
        ],
      },
      { title: 'CMV', path: '/stock/cmv', featureKey: 'stock_cmv', actionKey: 'read' },
      {
        title: 'Perdas e Ajustes',
        path: '/stock/adjustments',
        featureKey: 'stock_adjustments',
        actionKey: 'read',
      },
      {
        title: 'Lotes e Validades',
        path: '/stock/lots',
        featureKey: 'stock_lots',
        actionKey: 'read',
      },
      { title: 'Alertas', path: '/stock/alerts', featureKey: 'stock_alerts', actionKey: 'read' },
    ],
  },
  {
    module: 'orders',
    title: 'Pedidos',
    icon: <OrdersIcon />,
    roles: ['admin', 'owner', 'manager'],
    submenu: [
      {
        title: 'Painel',
        path: '/orders/dashboard',
        featureKey: 'orders_dashboard',
        actionKey: 'read',
      },
      { title: 'PDV', path: '/orders/pdv', featureKey: 'orders_pdv', actionKey: 'read' },
      { title: 'Pedidos', path: '/orders/list', featureKey: 'orders_list', actionKey: 'read' },
      {
        title: 'Integrações',
        path: '/orders/integrations',
        featureKey: 'orders_integrations',
        actionKey: 'read',
      },
      {
        title: 'Delivery',
        path: '/orders/delivery',
        featureKey: 'orders_delivery',
        actionKey: 'read',
      },
      {
        title: 'Relatorio de Vendas',
        path: '/orders/sales-report',
        featureKey: 'orders_sales_report',
        actionKey: 'read',
      },
      {
        title: 'Salão',
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Mesas',
            path: '/orders/tables',
            featureKey: 'orders_tables',
            actionKey: 'read',
          },
        ],
      },
    ],
  },
  {
    module: 'management',
    title: 'Gestão',
    icon: <ManagementIcon />,
    roles: ['admin', 'owner', 'manager'],
    submenu: [
      {
        title: 'Dashboard',
        path: '/management/dashboard',
        featureKey: 'management_dashboard',
        actionKey: 'read',
      },
      {
        title: 'Escala de Funcionarios',
        path: '/management/schedule',
        featureKey: 'management_schedule',
        actionKey: 'read',
      },
      {
        title: 'Controle de Comissões',
        path: '/management/commissions',
        featureKey: 'management_commissions',
        actionKey: 'read',
      },
      {
        title: 'Custos Fixos e Variaveis',
        path: '/management/costs',
        featureKey: 'management_costs',
        actionKey: 'read',
      },
      {
        title: 'Equipe',
        path: '/management/team',
        featureKey: 'management_team',
        actionKey: 'read',
      },
      {
        title: 'Produção',
        path: '/management/production',
        featureKey: 'management_production',
        actionKey: 'read',
      },
      {
        title: 'Permissões',
        path: '/management/permissions',
        featureKey: 'management_permissions',
        actionKey: 'read',
      },
    ],
  },
  {
    module: 'cdv',
    title: 'CDV',
    icon: <CdvIcon />,
    roles: ['admin', 'owner', 'manager'],
    submenu: [
      { title: 'Painel', path: '/cdv/dashboard', featureKey: 'cdv_dashboard', actionKey: 'read' },
      { title: 'Etiquetas', path: '/cdv/labels', featureKey: 'cdv_labels', actionKey: 'read' },
      {
        title: 'Impressão Etiquetas',
        path: '/cdv/labels/print',
        featureKey: 'cdv_labels_print',
        actionKey: 'read',
      },
      {
        title: 'Impressão em Grupo',
        path: '/cdv/labels/print-group',
        featureKey: 'cdv_labels_print_group',
        actionKey: 'read',
      },
      {
        title: 'Contagem de Etiquetas',
        path: '/cdv/labels/count',
        featureKey: 'cdv_labels_count',
        actionKey: 'read',
      },
      {
        title: 'Historico de Contagem',
        path: '/cdv/labels/count-history',
        featureKey: 'cdv_labels_count_history',
        actionKey: 'read',
      },
      {
        title: 'Historico de Etiquetas',
        path: '/cdv/labels/history',
        featureKey: 'cdv_labels_history',
        actionKey: 'read',
      },
      {
        title: 'Exclusão de Etiquetas',
        path: '/cdv/labels/delete',
        featureKey: 'cdv_labels_delete',
        actionKey: 'delete',
      },
      {
        title: 'Contagem de Estoque',
        path: '/cdv/stock-counts',
        featureKey: 'cdv_stock_counts',
        actionKey: 'read',
      },
      {
        title: 'Validades',
        path: '/cdv/expirations',
        featureKey: 'cdv_expirations',
        actionKey: 'read',
      },
      {
        title: 'Alerta de Validades',
        path: '/cdv/expirations-alert',
        featureKey: 'cdv_expirations_alert',
        actionKey: 'read',
      },
    ],
  },
  {
    module: 'financial',
    title: 'Financeiro',
    icon: <FinancialIcon />,
    roles: ['admin', 'owner', 'manager'],
    submenu: [
      {
        title: 'Contas a Pagar',
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Fornecedores',
            path: '/financial/payables/suppliers',
            featureKey: 'financial_payables_suppliers',
            actionKey: 'read',
          },
          {
            title: 'Prazos',
            path: '/financial/payables/deadlines',
            featureKey: 'financial_payables_deadlines',
            actionKey: 'read',
          },
          {
            title: 'Boletos',
            path: '/financial/payables/invoices',
            featureKey: 'financial_payables_invoices',
            actionKey: 'read',
          },
          {
            title: 'Recorrencia',
            path: '/financial/payables/recurring',
            featureKey: 'financial_payables_recurring',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Contas a Receber',
        path: '/financial/receivables',
        featureKey: 'financial_receivables',
        actionKey: 'read',
      },
      {
        title: 'Fluxo de Caixa',
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Painel',
            path: '/reports/cash-flow',
            featureKey: 'cash_flow_dashboard',
            actionKey: 'read',
          },
          {
            title: 'Visão',
            path: '/financial/cash-flow/view',
            featureKey: 'cash_flow_view',
            actionKey: 'read',
          },
          {
            title: 'Projeção',
            path: '/financial/cash-flow/projection',
            featureKey: 'cash_flow_projection',
            actionKey: 'read',
          },
          {
            title: 'Historico',
            path: '/financial/cash-flow/history',
            featureKey: 'cash_flow_history',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'DRE',
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          { title: 'Visão', path: '/reports/dre', featureKey: 'dre_view', actionKey: 'read' },
          {
            title: 'Receita',
            path: '/financial/dre/revenue',
            featureKey: 'dre_revenue',
            actionKey: 'read',
          },
          {
            title: 'Custo Variavel (CMV)',
            path: '/financial/dre/cmv',
            featureKey: 'dre_cmv',
            actionKey: 'read',
          },
          {
            title: 'Margem Bruta',
            path: '/financial/dre/gross-margin',
            featureKey: 'dre_gross_margin',
            actionKey: 'read',
          },
          {
            title: 'Custos Fixos',
            path: '/financial/dre/fixed-costs',
            featureKey: 'dre_fixed_costs',
            actionKey: 'read',
          },
          {
            title: 'Lucro Liquido',
            path: '/financial/dre/net-profit',
            featureKey: 'dre_net_profit',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Pagamentos',
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Meio de Pagamentos',
            path: '/erp/payment-methods',
            featureKey: 'payment_methods',
            actionKey: 'read',
          },
          {
            title: 'Taxas',
            path: '/financial/payments/fees',
            featureKey: 'payments_fees',
            actionKey: 'read',
          },
          {
            title: 'Relatorios',
            path: '/financial/payments/reports',
            featureKey: 'payments_reports',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Fiscal',
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Notas Fiscais',
            path: '/financial/fiscal/invoices',
            featureKey: 'fiscal_invoices',
            actionKey: 'read',
          },
          {
            title: 'Impostos',
            path: '/financial/fiscal/taxes',
            featureKey: 'fiscal_taxes',
            actionKey: 'read',
          },
          {
            title: 'Integração SEFAZ',
            path: '/financial/fiscal/sefaz',
            featureKey: 'fiscal_sefaz',
            actionKey: 'read',
          },
          {
            title: 'Relatórios',
            path: '/financial/fiscal/reports',
            featureKey: 'fiscal_reports',
            actionKey: 'read',
          },
          {
            title: 'Configurações',
            path: '/financial/fiscal/settings',
            featureKey: 'fiscal_settings',
            actionKey: 'read',
          },
        ],
      },
    ],
  },
  {
    title: 'Configurações',
    icon: <SettingsIcon />,
    roles: ['admin', 'owner'],
    submenu: [
      {
        title: 'Perfil',
        path: '/settings/profile',
        featureKey: 'user_profile',
        actionKey: 'update',
      },
      {
        title: 'Empresa',
        path: '/settings/business',
        featureKey: 'business_settings',
        actionKey: 'update',
      },
      {
        title: 'Segurança',
        path: '/settings/security',
        featureKey: 'security_settings',
        actionKey: 'update',
      },
      {
        title: 'WhatsApp',
        path: '/settings/whatsapp',
        featureKey: 'whatsapp_integration',
        actionKey: 'update',
      },
      {
        title: 'Notificações',
        path: '/settings/notifications',
        featureKey: 'notification_settings',
        actionKey: 'update',
      },
      {
        title: 'Aparência',
        path: '/settings/appearance',
        featureKey: 'appearance_settings',
        actionKey: 'update',
      },
    ],
  },
  {
    title: 'Admin',
    icon: <AdminIcon />,
    roles: ['super_admin'],
    submenu: [
      {
        title: 'Usuários',
        path: '/admin/users',
        featureKey: 'admin_users',
        actionKey: 'read',
      },
      {
        title: 'Restaurantes',
        path: '/admin/restaurants',
        featureKey: 'admin_restaurants',
        actionKey: 'read',
      },
      {
        title: 'Permissões',
        path: '/admin/roles-permissions',
        featureKey: 'admin_roles_permissions',
        actionKey: 'read',
      },
    ],
  },
];
