import {
  Settings as SettingsIcon,
  Person as PersonIcon,
  AdminPanelSettings as AdminPanelSettingsIcon,
  Dashboard as DashboardIcon,
  CheckBox as CheckinIcon,
  Star as SatisfactionIcon,
  Chat as ResponsesIcon,
  ConnectWithoutContact as RelationshipIcon,
  CardGiftcard as CouponsIcon,
  Sync as AutomationIcon,
  Settings as IntegrationsIcon,
  Assessment as ReportsIcon,
} from '@mui/icons-material';

export const menuConfig = [
  {
    module: 'fidelity',
    title: 'Fidelidade',
    icon: <DashboardIcon />,
    roles: ['admin', 'owner', 'manager'],
    submenu: [
      {
        title: 'Geral',
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Painel Inicial',
            path: '/fidelity/dashboard',
            featureKey: 'fidelity:general:dashboard',
            actionKey: 'read',
          },
          {
            title: 'Resumo do mês',
            path: '/fidelity/monthly-summary',
            featureKey: 'fidelity:general:monthly-summary',
            actionKey: 'read',
          },
          {
            title: 'Satisfação',
            path: '/fidelity/satisfaction-overview',
            featureKey: 'fidelity:general:satisfaction-overview',
            actionKey: 'read',
          },
          {
            title: 'Comparativo Pesquisas',
            path: '/fidelity/surveys-comparison',
            featureKey: 'fidelity:general:surveys-comparison',
            actionKey: 'read',
          },
          {
            title: 'Evolução',
            path: '/fidelity/evolution',
            featureKey: 'fidelity:general:evolution',
            actionKey: 'read',
          },
          {
            title: 'Benchmarking',
            path: '/fidelity/benchmarking',
            featureKey: 'fidelity:general:benchmarking',
            actionKey: 'read',
          },
          {
            title: 'Multipla Escolha',
            path: '/fidelity/multiple-choice',
            featureKey: 'fidelity:general:multiple-choice',
            actionKey: 'read',
          },
          {
            title: 'Nuvens de Palavras',
            path: '/fidelity/word-clouds',
            featureKey: 'fidelity:general:word-clouds',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Check in',
        icon: <CheckinIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Dashboard',
            path: '/fidelity/checkin/dashboard',
            featureKey: 'fidelity:checkin:dashboard',
            actionKey: 'read',
          },
          {
            title: 'Configurações',
            path: '/fidelity/checkin/settings',
            featureKey: 'fidelity:checkin:settings',
            actionKey: 'read',
          },
          {
            title: 'Checkin Ativos',
            path: '/fidelity/checkin/active',
            featureKey: 'fidelity:checkin:active',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Satisfação',
        icon: <SatisfactionIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Dashboard',
            path: '/fidelity/satisfaction/dashboard',
            featureKey: 'fidelity:satisfaction:dashboard',
            actionKey: 'read',
          },
          {
            title: 'Configurações',
            path: '/fidelity/satisfaction/settings',
            featureKey: 'fidelity:satisfaction:settings',
            actionKey: 'read',
          },
          {
            title: 'Pesquisas',
            path: '/fidelity/satisfaction/surveys',
            featureKey: 'fidelity:satisfaction:surveys',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Respostas',
        icon: <ResponsesIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Painel',
            path: '/fidelity/responses/dashboard',
            featureKey: 'fidelity:responses:dashboard',
            actionKey: 'read',
          },
          {
            title: 'Gestão as Respostas',
            path: '/fidelity/responses/management',
            featureKey: 'fidelity:responses:management',
            actionKey: 'read',
          },
          {
            title: 'Replicas',
            path: '/fidelity/responses/replicas',
            featureKey: 'fidelity:responses:replicas',
            actionKey: 'read',
          },
          {
            title: 'Metas',
            path: '/fidelity/responses/goals',
            featureKey: 'fidelity:responses:goals',
            actionKey: 'read',
          },
          {
            title: 'Importar',
            path: '/fidelity/responses/import',
            featureKey: 'fidelity:responses:import',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Relacionamento',
        icon: <RelationshipIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Dashboard',
            path: '/fidelity/relationship/dashboard',
            featureKey: 'fidelity:relationship:dashboard',
            actionKey: 'read',
          },
          {
            title: 'Ranking de Clientes',
            path: '/fidelity/relationship/ranking',
            featureKey: 'fidelity:relationship:ranking',
            actionKey: 'read',
          },
          {
            title: 'Disparos',
            path: '/fidelity/relationship/dispatches',
            featureKey: 'fidelity:relationship:dispatches',
            actionKey: 'read',
          },
          {
            title: 'Campanhas Automaticas',
            path: '/fidelity/relationship/campaigns',
            featureKey: 'fidelity:relationship:campaigns',
            actionKey: 'read',
          },
          {
            title: 'Mensagens',
            path: '/fidelity/relationship/messages',
            featureKey: 'fidelity:relationship:messages',
            actionKey: 'read',
          },
          {
            title: 'Aniversariantes',
            path: '/fidelity/relationship/birthdays',
            featureKey: 'fidelity:relationship:birthdays',
            actionKey: 'read',
          },
          {
            title: 'Gestão de Clientes',
            path: '/fidelity/relationship/customers',
            featureKey: 'fidelity:relationship:customers',
            actionKey: 'read',
          },
          {
            title: 'Segmentação de Clientes',
            path: '/fidelity/relationship/segmentation',
            featureKey: 'fidelity:relationship:segmentation',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Cupons',
        icon: <CouponsIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Painel',
            path: '/fidelity/coupons/dashboard',
            featureKey: 'fidelity:coupons:dashboard',
            actionKey: 'read',
          },
          {
            title: 'Cupons',
            path: '/fidelity/coupons/list',
            featureKey: 'fidelity:coupons:list',
            actionKey: 'read',
          },
          {
            title: 'Gestão de Cupons',
            path: '/fidelity/coupons/management',
            featureKey: 'fidelity:coupons:management',
            actionKey: 'read',
          },
          {
            title: 'Validação',
            path: '/fidelity/coupons/validation',
            featureKey: 'fidelity:coupons:validation',
            actionKey: 'read',
          },
          {
            title: 'Sorteio',
            path: '/fidelity/coupons/raffle',
            featureKey: 'fidelity:coupons:raffle',
            actionKey: 'read',
          },
          {
            title: 'Recompensas',
            path: '/fidelity/coupons/rewards',
            featureKey: 'fidelity:coupons:rewards',
            actionKey: 'read',
          },
          {
            title: 'Gestão de Recompensas',
            path: '/fidelity/coupons/rewards-management',
            featureKey: 'fidelity:coupons:rewards-management',
            actionKey: 'read',
          },
          {
            title: 'Cadastro de Recompensas',
            path: '/fidelity/coupons/rewards-create',
            featureKey: 'fidelity:coupons:rewards-create',
            actionKey: 'create',
          },
          {
            title: 'Relatorios de Resgate',
            path: '/fidelity/coupons/redemption-reports',
            featureKey: 'fidelity:coupons:redemption-reports',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Automação',
        icon: <AutomationIcon />,
        roles: ['admin', 'owner', 'manager'],
        submenu: [
          {
            title: 'Fluxos',
            path: '/fidelity/automation/flows',
            featureKey: 'fidelity:automation:flows',
            actionKey: 'read',
          },
        ],
      },
      {
        title: 'Integrações',
        icon: <IntegrationsIcon />,
        path: '/fidelity/integrations',
        featureKey: 'fidelity:integrations',
        actionKey: 'read',
      },
      {
        title: 'Relatorios',
        icon: <ReportsIcon />,
        path: '/fidelity/reports',
        featureKey: 'fidelity:reports',
        actionKey: 'read',
      },
    ],
  },
  {
    module: 'admin',
    title: 'Admin',
    icon: <AdminPanelSettingsIcon />,
    roles: ['super_admin'],
    submenu: [
      {
        title: 'Usuários',
        path: '/admin/users',
        featureKey: 'users',
        actionKey: 'read',
      },
      {
        title: 'Restaurantes',
        path: '/admin/restaurants',
        featureKey: 'restaurants',
        actionKey: 'read',
      },
      {
        title: 'Permissões',
        path: '/admin/roles-permissions',
        featureKey: 'role_management',
        actionKey: 'read',
      },
      {
        title: 'Gerenciamento de Módulos',
        path: '/admin/restaurant-modules',
        featureKey: 'modules',
        actionKey: 'manage',
      },
    ],
  },
  {
    module: 'customers',
    title: 'Clientes',
    icon: <PersonIcon />,
    roles: ['admin', 'owner', 'manager'],
    submenu: [
      {
        title: 'Visão Geral',
        path: '/customers/dashboard',
        featureKey: 'customers:dashboard',
        actionKey: 'read',
      },
      {
        title: 'Lista de Clientes',
        path: '/customers/list',
        featureKey: 'customers:list',
        actionKey: 'read',
      },
      {
        title: 'Aniversariantes',
        path: '/customers/birthdays',
        featureKey: 'customers:birthdays',
        actionKey: 'read',
      },
    ],
  },
  {
    module: 'settings',
    title: 'Configurações',
    icon: <SettingsIcon />,
    roles: ['admin', 'owner'],
    submenu: [
      {
        title: 'Perfil',
        path: '/settings/profile',
        featureKey: 'user_profile',
        actionKey: 'update',
      },
      {
        title: 'Empresa',
        path: '/settings/business',
        featureKey: 'business_settings',
        actionKey: 'update',
      },
      {
        title: 'Notificações',
        path: '/settings/notifications',
        featureKey: 'notification_settings',
        actionKey: 'update',
      },
      {
        title: 'Segurança',
        path: '/settings/security',
        featureKey: 'security_settings',
        actionKey: 'update',
      },
      {
        title: 'Aparência',
        path: '/settings/appearance',
        featureKey: 'appearance_settings',
        actionKey: 'update',
      },
      {
        title: 'WhatsApp',
        path: '/settings/whatsapp',
        featureKey: 'whatsapp_integration',
        actionKey: 'update',
      },
    ],
  },
];